server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: prod
    default: dev
    include:
      - security
      - secret
      - domain
      - aws
